/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as guestRegisterRouteImport } from './routes/(guest)/register'
import { Route as guestLoginRouteImport } from './routes/(guest)/login'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const guestRegisterRoute = guestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => guestRouteRoute,
} as any)
const guestLoginRoute = guestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => guestRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof guestLoginRoute
  '/register': typeof guestRegisterRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof guestLoginRoute
  '/register': typeof guestRegisterRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(guest)': typeof guestRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/(guest)/login': typeof guestLoginRoute
  '/(guest)/register': typeof guestRegisterRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/login' | '/register' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/app'
  id:
    | '__root__'
    | '/'
    | '/(guest)'
    | '/app'
    | '/(guest)/login'
    | '/(guest)/register'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  guestRouteRoute: typeof guestRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(guest)/register': {
      id: '/(guest)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof guestRegisterRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(guest)/login': {
      id: '/(guest)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestLoginRouteImport
      parentRoute: typeof guestRouteRoute
    }
  }
}

interface guestRouteRouteChildren {
  guestLoginRoute: typeof guestLoginRoute
  guestRegisterRoute: typeof guestRegisterRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestLoginRoute: guestLoginRoute,
  guestRegisterRoute: guestRegisterRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  guestRouteRoute: guestRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
