/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as guestRegisterRouteImport } from './routes/(guest)/register'
import { Route as guestLoginRouteImport } from './routes/(guest)/login'
import { Route as protectedAppRouteRouteImport } from './routes/(protected)/app/route'
import { Route as protectedAppIndexRouteImport } from './routes/(protected)/app/index'
import { Route as protectedAppStatsIndexRouteImport } from './routes/(protected)/app/stats/index'
import { Route as protectedAppGameIndexRouteImport } from './routes/(protected)/app/game/index'
import { Route as protectedAppGameNewRouteImport } from './routes/(protected)/app/game/new'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRegisterRoute = guestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => guestRouteRoute,
} as any)
const guestLoginRoute = guestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => guestRouteRoute,
} as any)
const protectedAppRouteRoute = protectedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAppIndexRoute = protectedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedAppRouteRoute,
} as any)
const protectedAppStatsIndexRoute = protectedAppStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => protectedAppRouteRoute,
} as any)
const protectedAppGameIndexRoute = protectedAppGameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => protectedAppRouteRoute,
} as any)
const protectedAppGameNewRoute = protectedAppGameNewRouteImport.update({
  id: '/game/new',
  path: '/game/new',
  getParentRoute: () => protectedAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof protectedAppRouteRouteWithChildren
  '/login': typeof guestLoginRoute
  '/register': typeof guestRegisterRoute
  '/app/': typeof protectedAppIndexRoute
  '/app/game/new': typeof protectedAppGameNewRoute
  '/app/game': typeof protectedAppGameIndexRoute
  '/app/stats': typeof protectedAppStatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof guestLoginRoute
  '/register': typeof guestRegisterRoute
  '/app': typeof protectedAppIndexRoute
  '/app/game/new': typeof protectedAppGameNewRoute
  '/app/game': typeof protectedAppGameIndexRoute
  '/app/stats': typeof protectedAppStatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(protected)/app': typeof protectedAppRouteRouteWithChildren
  '/(guest)/login': typeof guestLoginRoute
  '/(guest)/register': typeof guestRegisterRoute
  '/(protected)/app/': typeof protectedAppIndexRoute
  '/(protected)/app/game/new': typeof protectedAppGameNewRoute
  '/(protected)/app/game/': typeof protectedAppGameIndexRoute
  '/(protected)/app/stats/': typeof protectedAppStatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/'
    | '/app/game/new'
    | '/app/game'
    | '/app/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/game/new'
    | '/app/game'
    | '/app/stats'
  id:
    | '__root__'
    | '/'
    | '/(guest)'
    | '/(protected)'
    | '/(protected)/app'
    | '/(guest)/login'
    | '/(guest)/register'
    | '/(protected)/app/'
    | '/(protected)/app/game/new'
    | '/(protected)/app/game/'
    | '/(protected)/app/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  guestRouteRoute: typeof guestRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/register': {
      id: '/(guest)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof guestRegisterRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(guest)/login': {
      id: '/(guest)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestLoginRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(protected)/app': {
      id: '/(protected)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof protectedAppRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/app/': {
      id: '/(protected)/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof protectedAppIndexRouteImport
      parentRoute: typeof protectedAppRouteRoute
    }
    '/(protected)/app/stats/': {
      id: '/(protected)/app/stats/'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof protectedAppStatsIndexRouteImport
      parentRoute: typeof protectedAppRouteRoute
    }
    '/(protected)/app/game/': {
      id: '/(protected)/app/game/'
      path: '/game'
      fullPath: '/app/game'
      preLoaderRoute: typeof protectedAppGameIndexRouteImport
      parentRoute: typeof protectedAppRouteRoute
    }
    '/(protected)/app/game/new': {
      id: '/(protected)/app/game/new'
      path: '/game/new'
      fullPath: '/app/game/new'
      preLoaderRoute: typeof protectedAppGameNewRouteImport
      parentRoute: typeof protectedAppRouteRoute
    }
  }
}

interface guestRouteRouteChildren {
  guestLoginRoute: typeof guestLoginRoute
  guestRegisterRoute: typeof guestRegisterRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestLoginRoute: guestLoginRoute,
  guestRegisterRoute: guestRegisterRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

interface protectedAppRouteRouteChildren {
  protectedAppIndexRoute: typeof protectedAppIndexRoute
  protectedAppGameNewRoute: typeof protectedAppGameNewRoute
  protectedAppGameIndexRoute: typeof protectedAppGameIndexRoute
  protectedAppStatsIndexRoute: typeof protectedAppStatsIndexRoute
}

const protectedAppRouteRouteChildren: protectedAppRouteRouteChildren = {
  protectedAppIndexRoute: protectedAppIndexRoute,
  protectedAppGameNewRoute: protectedAppGameNewRoute,
  protectedAppGameIndexRoute: protectedAppGameIndexRoute,
  protectedAppStatsIndexRoute: protectedAppStatsIndexRoute,
}

const protectedAppRouteRouteWithChildren =
  protectedAppRouteRoute._addFileChildren(protectedAppRouteRouteChildren)

interface protectedRouteRouteChildren {
  protectedAppRouteRoute: typeof protectedAppRouteRouteWithChildren
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedAppRouteRoute: protectedAppRouteRouteWithChildren,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  guestRouteRoute: guestRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
